/*
Code generated by Carto Workflows Engine (RUN)
- workflowid:a412059b-60e0-474c-897f-83aa7f342bc1
- versionid:8858c9fea91dfab7
- paramsid:97d170e1550eee4a
*/

/*==================== native.intersection (v1) [3a1d1c84-8dd3-49d6-b37a-8e3c9ac84f5c]  ====================*/
BEGIN
DECLARE alias STRING;

EXECUTE IMMEDIATE
'''
  with __alias AS(
    SELECT CONCAT(
      'b.', column_name, ' AS ', column_name, '_secondary'
    ) col_alias
    FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3`.INFORMATION_SCHEMA.COLUMNS
  WHERE table_name = 'distritos'
  )
  SELECT STRING_AGG(col_alias, ', ')
  FROM __alias
'''
INTO alias;

EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_87633ce227709ca8_result`''',
  '%s',
  alias
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_87633ce227709ca8_result`
  OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(
      CURRENT_TIMESTAMP(), INTERVAL 30 DAY
    )
  )
  AS
    SELECT
      ST_INTERSECTION(
        b.geom,
        a.geom
      )
    AS intersection_geom_geom,
      a.*, %s
    FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentalidad_sin_distrito` AS a
    JOIN `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.distritos` AS b
    ON ST_INTERSECTS(
      b.geom,
      a.geom
    )''',
  '%s',
  alias
);
END;

/*==================== native.dropcolumn (v1) [6a5304bd-f1e0-4ea7-9492-5416b8e62dae]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_30e9f569e85ef7e2_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_30e9f569e85ef7e2_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (intersection_geom_geom, geom_secondary)
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_87633ce227709ca8_result`;
END;

/*==================== native.renamecolumn (v1) [5f459751-5e57-4c59-959c-c46c2421032a]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_243221859e77d290_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_243221859e77d290_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (distrito_secondary),
    distrito_secondary AS distrito
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_30e9f569e85ef7e2_result`;
END;

/*==================== native.saveastable (v1) [e6e4bf59-c328-4149-a4f8-7833c3e6c1a0]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentalidad';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_243221859e77d290_result`''',
  '####',
  __destination
);
END;
END;

/*==================== SaveToBucketAndNotify (v2) [61c13242-1eab-413e-b8bf-1307f8621b40]  ====================*/
BEGIN

        DECLARE emails STRING DEFAULT '''["jorgekk22@gmail.com"]''';
        DECLARE export_id STRING DEFAULT GENERATE_UUID();
        DECLARE bucket STRING DEFAULT 'carto-tnt-gcp-europe-west1-export-storage';
        DECLARE response STRING;
        DECLARE headers STRING DEFAULT '''
        { "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI5YTg2Y2YzZSJ9.gYbWO0R1rkzFjjIks-fyNMpqxFIX0d_7ze72QhXNScQ",
          "Content-Type": "application/json"
        }''';
        DECLARE bucket_urls STRING;
        DECLARE payload STRING;
        EXECUTE IMMEDIATE FORMAT('''
          EXPORT DATA -- carto-export-id: %s
            OPTIONS (
              uri = 'gs://%s/%s-*.csv.gz',
              format = 'CSV',
              overwrite = true,
              compression = 'GZIP',
        header = true,
        field_delimiter = ','
          )
          AS (
            SELECT * FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentalidad`
          )
         ''',
         export_id, bucket, export_id
         );
        SET bucket_urls = (
          WITH export_result AS (
            SELECT timeline[0].pending_units + timeline[0].completed_units AS num_files
            FROM `carto-dw-ac-t872o53f`.`region-EU`.INFORMATION_SCHEMA.JOBS_BY_USER
            WHERE creation_time > TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL -1 HOUR)
              AND statement_type = 'EXPORT_DATA'
              AND query LIKE CONCAT('%', '-- carto-export-id: ', export_id, '%')
            LIMIT 1
          )
          SELECT ARRAY_TO_STRING(ARRAY(
            SELECT CONCAT(
              '"',
              'https://storage.googleapis.com/',
              bucket,
              '/',
              export_id,
              '-',
              LPAD(CAST(i AS STRING), 12, '0'),
              '.',
              'csv',
              '.gz',
              '"'
            ) AS url
            FROM export_result, UNNEST(GENERATE_ARRAY(0, num_files - 1)) AS i
            ORDER BY i), ', ')
        );
        SET payload = CONCAT('''
          {
            "method": "email",
            "payload": {
              "emails": ''', emails, ''',
              "subject": "accidentalidad",
              "body": "<br><ul>{% for bucketUrl in bucketUrls %}<li>{{ bucketUrl }}</li>{% endfor %}</ul>",
              "replacements": {
                "bucketUrls": [ ''', bucket_urls, ''']
              }
            }
          }
          '''
        );
        SET response = `carto-un-eu.carto.__REQUEST`(
          'post', 'https://gcp-europe-west1.api.carto.com',
          'v3/workflows/notify', payload, headers
        );

END;

/*==================== native.dropcolumn (v1) [f2d26391-f3c4-413d-ba89-8c4c652023cd]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_5ac1103717aceed3_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_5ac1103717aceed3_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (tipo_vehiculo_clasificado, tipo_persona, rango_edad, sexo, lesividad_clasificada, positiva_alcohol, positiva_droga)
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_243221859e77d290_result`;
END;

/*==================== native.removeduplicatedrows (v1) [edb63c9b-7c59-4de0-bebe-b4cf11b7302f]  ====================*/
BEGIN
DECLARE alias_encoded STRING;
DECLARE alias_decoded STRING;

EXECUTE IMMEDIATE
'''
  with __alias AS(
    SELECT REPLACE(
      CASE data_type WHEN 'GEOGRAPHY' THEN 'ST_ASBINARY(%s) AS %s' ELSE '%s AS %s' END
    , '%s', column_name) col_alias_encoded,
    REPLACE(
      CASE data_type WHEN 'GEOGRAPHY' THEN 'ST_GEOGFROMWKB(%s) AS %s' ELSE '%s AS %s' END
    , '%s', column_name) col_alias_decoded
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3`.INFORMATION_SCHEMA.COLUMNS
  WHERE table_name = 'WORKFLOW_8cb51442ff57d51e_5ac1103717aceed3_result'
  )
  SELECT STRING_AGG(col_alias_encoded, ', '), STRING_AGG(col_alias_decoded, ', ')
  FROM __alias
'''
INTO alias_encoded, alias_decoded;

EXECUTE IMMEDIATE
REPLACE(
  REPLACE(
    '''DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_a9fb81e85d4158b3_result`''',
    '%s1',
    alias_decoded
  ),
  '%s2',
  alias_encoded
);
EXECUTE IMMEDIATE
REPLACE(
  REPLACE(
    '''CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_a9fb81e85d4158b3_result`
    OPTIONS (
      expiration_timestamp = TIMESTAMP_ADD(
        CURRENT_TIMESTAMP(), INTERVAL 30 DAY
      )
    )
    AS
      SELECT %s1
      FROM (SELECT DISTINCT %s2 FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_5ac1103717aceed3_result`)''',
    '%s1',
    alias_decoded
  ),
  '%s2',
  alias_encoded
);
END;

/*==================== native.saveastable (v1) [26a19292-8422-4aa3-b8a4-65c17980032e]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentes';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_a9fb81e85d4158b3_result`''',
  '####',
  __destination
);
END;
END;

/*==================== native.sample (v1) [5eb7e347-2258-4de9-b574-e38af9889272]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_36843e5e4ffedaf1_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_36843e5e4ffedaf1_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_a9fb81e85d4158b3_result`
  ORDER BY RAND()
  LIMIT 1000;
END;

/*==================== native.saveastable (v1) [539d66b4-84d5-414b-b2e3-6c9d08845f71]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentes_sample';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_36843e5e4ffedaf1_result`''',
  '####',
  __destination
);
END;
END;

/*==================== native.join (v1.2) [381809b0-69c7-482d-a01c-64f7f29cae7c]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_1215d2ec83f4eb00_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_1215d2ec83f4eb00_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT 
    _main.*,
    _joined.distrito AS distrito_joined, _joined.geom AS geom_joined, _joined.num_expediente AS num_expediente_joined, _joined.fecha AS fecha_joined, _joined.tipo_accidente_clasificado AS tipo_accidente_clasificado_joined, _joined.estado_meteorologico AS estado_meteorologico_joined, _joined.anno AS anno_joined, _joined.mes AS mes_joined, _joined.dia_mes AS dia_mes_joined, _joined.dia_semana AS dia_semana_joined, _joined.horas AS horas_joined, _joined.hora_rango AS hora_rango_joined
  FROM
    `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_243221859e77d290_result` AS _main
  INNER JOIN
    `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_36843e5e4ffedaf1_result` AS _joined
  ON
    _main.num_expediente = _joined.num_expediente;
END;

/*==================== native.dropcolumn (v1) [dd23a5b7-1138-4894-bbae-fa4f874703a0]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_07d11446c3ed09e5_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_07d11446c3ed09e5_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (distrito_joined, geom_joined, num_expediente_joined, fecha_joined, tipo_accidente_clasificado_joined, estado_meteorologico_joined, anno_joined, mes_joined, dia_mes_joined, dia_semana_joined, horas_joined, hora_rango_joined)
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_1215d2ec83f4eb00_result`;
END;

/*==================== native.saveastable (v1) [1a484935-a01d-41fc-9303-56988528b6c2]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentalidad_sample';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_8cb51442ff57d51e_07d11446c3ed09e5_result`''',
  '####',
  __destination
);
END;
END;