/*
Code generated by Carto Workflows Engine (RUN)
- workflowid:3cb90fdd-7a0b-4afa-b760-e9f7470f8d67
- versionid:a76dc1c799d87eb0
- paramsid:97d170e1550eee4a
*/

/*==================== native.clusterdbscan (v1) [e8c2ef61-5a5e-4e32-a54d-4fb5657e98a9]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3cd3b513dc04af3c_55c1b3f7d4d377f6_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3cd3b513dc04af3c_55c1b3f7d4d377f6_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    ST_CLUSTERDBSCAN(
      geom,
      15,
      25
    )
    OVER () AS cluster
  FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentes`;
END;

/*==================== native.customsql (v2.0.0) [fc1a70d3-5f90-486b-9dde-c4ce8dd4d288]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3cd3b513dc04af3c_82745b97b47d19dc_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3cd3b513dc04af3c_82745b97b47d19dc_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  
  
  WITH
    
    clustered_points AS (
      SELECT
        *
      FROM
        `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3cd3b513dc04af3c_55c1b3f7d4d377f6_result` 
      WHERE
        cluster IS NOT NULL
        AND ST_GEOMETRYTYPE(geom) = 'ST_Point'
    ),
  
    
    cluster_polygons AS (
      SELECT
        cluster,
        
        COUNT(*) AS num_accidentes,
        
        
        COUNTIF(tipo_accidente_clasificado = 'Colisión doble') AS count_colision_doble,
        COUNTIF(tipo_accidente_clasificado = 'Alcance') AS count_alcance,
        COUNTIF(tipo_accidente_clasificado = 'Atropello a persona') AS count_atropello,
        COUNTIF(tipo_accidente_clasificado = 'Choque contra obstáculo') AS count_obstaculo,
        
        
        COUNTIF(estado_meteorologico = 'Lluvia intensa') AS count_lluvia,
        COUNTIF(estado_meteorologico = 'Nublado') AS count_nublado,
        
        
        ST_CONVEXHULL(ST_UNION_AGG(geom)) AS geom
      FROM
        clustered_points
      GROUP BY
        cluster
      HAVING
        COUNT(*) > 2 
    )
  
  
  SELECT
    *
  FROM
    cluster_polygons;
END;

/*==================== native.saveastable (v1) [bc1029fc-a6a6-474e-bfc6-6b52c5f57c16]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.dbscan_intersecciones_criticas';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3cd3b513dc04af3c_82745b97b47d19dc_result`''',
  '####',
  __destination
);
END;
END;