/*
Code generated by Carto Workflows Engine (RUN)
- workflowid:ad46aa14-82db-47f1-a395-517edadba387
- versionid:a187e977d9eff8fe
- paramsid:97d170e1550eee4a
*/

/*==================== native.wheresimplified (v1) [4a70cbb3-0bbd-4d70-9cca-b1df5a34ab39]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_8ea63dfdd84f3ac8_match`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_8ea63dfdd84f3ac8_match`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *
  FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales`
  WHERE
    nombre = 'Hospital Universitario la Paz';

END;

/*==================== native.isolines (v2) [89cddc6f-9708-4708-b05f-ddffb30d5291]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_4771a1188c0d06a8_result`;
BEGIN
  
  CALL `carto-un-eu.carto`.CREATE_ISOLINES(
    'https://gcp-europe-west1.api.carto.com',
    'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI2NDY2ZDg4MyJ9.YJG_H6JsBlqZuWeqAd_QCxNcjTSElcV3_DAKjF5gaaQ',
    'SELECT * FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_8ea63dfdd84f3ac8_match`',
    'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_4771a1188c0d06a8_result',
    'geom',
    'car',
    2500,
    'distance',
    '{"polygons_filter":{"limit":1},"carto_keep_orig_geom":true}');
  
END;
END;

/*==================== native.isolines (v2) [a40160e9-4940-4a76-a52e-25079b168317]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_ad5990499318251c_result`;
BEGIN
  
  CALL `carto-un-eu.carto`.CREATE_ISOLINES(
    'https://gcp-europe-west1.api.carto.com',
    'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI2NDY2ZDg4MyJ9.YJG_H6JsBlqZuWeqAd_QCxNcjTSElcV3_DAKjF5gaaQ',
    'SELECT * FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_8ea63dfdd84f3ac8_match`',
    'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_ad5990499318251c_result',
    'geom',
    'car',
    600,
    'time',
    '{"polygons_filter":{"limit":1},"carto_keep_orig_geom":true}');
  
END;
END;

/*==================== native.join (v1.2) [b0a8d34e-3a0b-41b6-b147-9461f5a40f6e]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_6fd5191c3a055a70_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_6fd5191c3a055a70_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT 
    _main.*,
    _joined.geom AS geom_joined, _joined.carto_isoline_metadata AS carto_isoline_metadata_joined, _joined.nombre AS nombre_joined
  FROM
    `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_ad5990499318251c_result` AS _main
  INNER JOIN
    `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_4771a1188c0d06a8_result` AS _joined
  ON
    _main.nombre = _joined.nombre;
END;

/*==================== native.dropcolumn (v1) [0fea438f-d045-4dd8-bfcd-3e4ad81b5e89]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_ae070c3e9223587f_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_ae070c3e9223587f_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (nombre_joined, carto_isoline_metadata_joined, carto_isoline_metadata)
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_6fd5191c3a055a70_result`;
END;

/*==================== native.renamecolumn (v1) [e6bdc840-ad30-4f33-8828-f3eaab5ff498]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_89dc5930ef434a65_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_89dc5930ef434a65_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (geom),
    geom AS isocrona
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_ae070c3e9223587f_result`;
END;

/*==================== native.renamecolumn (v1) [3c66a1ac-1a80-4b73-adea-9e5e342b35bf]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_e61f45a112f76cd8_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_e61f45a112f76cd8_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (geom_joined),
    geom_joined AS isodistancia
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_89dc5930ef434a65_result`;
END;

/*==================== native.saveastable (v1) [1e80067d-4ee3-4ef7-83d2-8e87f7f500a4]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospital_isocrona_isodistancia';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_3d9ac53530e93e18_e61f45a112f76cd8_result`''',
  '####',
  __destination
);
END;
END;