/*
Code generated by Carto Workflows Engine (RUN)
- workflowid:2617c781-ee0e-4d7a-b649-4a9fa02125c3
- versionid:f199830a9b206820
- paramsid:97d170e1550eee4a
*/

/*==================== native.h3frompoint (v1) [c8155fac-2fc1-4136-85cd-5582e68e7b46]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_f107384622ee8b2c_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_f107384622ee8b2c_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
  `carto-un-eu.carto`.H3_FROMGEOGPOINT(
      geom, 9
    ) h3, *
  FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentes`;
END;

/*==================== native.groupby (v1) [4779dff1-8f20-473b-8871-b750c99b1822]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_2ace5729ce7ccb1f_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_2ace5729ce7ccb1f_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT h3,
    COUNT(num_expediente) num_expediente_count
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_f107384622ee8b2c_result`
  GROUP BY h3;
END;

/*==================== native.renamecolumn (v1) [486d99e7-0f45-47b1-85c0-9f6cf2155666]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (num_expediente_count),
    num_expediente_count AS volumen_total_accidentes
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_2ace5729ce7ccb1f_result`;
END;

/*==================== native.getisord (v1) [ccc3745b-59bd-4d56-9f70-7e3f34d57e00]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_76d28c3461645342_result`;
BEGIN
  DECLARE grid_type STRING;
  DECLARE grid_resolution INT64;
  
  CALL `carto-un-eu.carto`.__CHECK_GRID_INDEX_COLUMN(
      'SELECT * FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result`',
      'h3',
      grid_type,
      grid_resolution
  );
  
  IF grid_type = 'quadbin' THEN
      CALL `carto-un-eu.carto`.GETIS_ORD_QUADBIN_TABLE(
          'SELECT * FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result`',
          'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_76d28c3461645342_result',
          'h3',
          'volumen_total_accidentes',
          1,
          'uniform'
      );
  ELSEIF grid_type = 'h3' THEN
      CALL `carto-un-eu.carto`.GETIS_ORD_H3_TABLE(
          'SELECT * FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result`',
          'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_76d28c3461645342_result',
          'h3',
          'volumen_total_accidentes',
          1,
          'uniform'
      );
  ELSE
      RAISE USING MESSAGE = 'Invalid spatial index column, please select a column that contains h3 or quadbin indexes.';
  END IF;
  
END;
END;

/*==================== native.h3boundary (v1) [1a448d71-b4f8-4695-9b50-9866bb559ebd]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_27e3f016ecdb8e59_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_27e3f016ecdb8e59_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
    `carto-un-eu.carto`.H3_BOUNDARY(
        index
    ) index_geo, *
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_76d28c3461645342_result`;
END;

/*==================== native.saveastable (v1) [ee8e3462-2a48-4493-aa4b-1ba1e6d50264]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.Getis_Ord';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_27e3f016ecdb8e59_result`''',
  '####',
  __destination
);
END;
END;

/*==================== native.localmoransi (v1) [a6e9387f-5b6e-43a5-9d79-f5132dd67ce6]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_331e7ee7b418a83f_result`;
BEGIN
  DECLARE grid_type STRING;
  DECLARE grid_resolution INT64;
  
  CALL `carto-un-eu.carto`.__CHECK_GRID_INDEX_COLUMN(
    'SELECT * FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result`',
    'h3',
    grid_type,
    grid_resolution
  );
  
  IF grid_type = 'quadbin' THEN
    CALL `carto-un-eu.carto`.LOCAL_MORANS_I_QUADBIN_TABLE(
      'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result',
      '`carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_331e7ee7b418a83f_result`',
      'h3',
      'volumen_total_accidentes',
      1,
      'uniform',
      99
    );
  ELSEIF grid_type = 'h3' THEN
    CALL `carto-un-eu.carto`.LOCAL_MORANS_I_H3_TABLE(
      'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_d72616ffe9572f1b_result',
      '`carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_331e7ee7b418a83f_result`',
      'h3',
      'volumen_total_accidentes',
      1,
      'uniform',
      99
    );
  ELSE
    RAISE USING MESSAGE = 'Invalid spatial index column, please select a column that contains h3 or quadbin indexes.';
  END IF;
  
END;
END;

/*==================== native.h3boundary (v1) [1805ac68-67ef-4212-835f-1f0b1291817f]  ====================*/
BEGIN
DROP TABLE IF EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_3836c024e838d2b3_result`;
CREATE OR REPLACE TABLE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_3836c024e838d2b3_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
    `carto-un-eu.carto`.H3_BOUNDARY(
        index
    ) index_geo, *
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_331e7ee7b418a83f_result`;
END;

/*==================== native.saveastable (v1) [0c420bca-2ad8-413c-8007-76892fd5f6fc]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.Local_Morans_I';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_595e93c05637805c_3836c024e838d2b3_result`''',
  '####',
  __destination
);
END;
END;