/*
Code generated by Carto Workflows Engine (RUN)
- workflowid:8f4e78d8-21c0-435b-bcc6-a50fd389c306
- versionid:3b1d3f0cff97501c
- paramsid:97d170e1550eee4a
*/

/*==================== native.h3frompoint (v1) [3bafd4d7-4b3f-4352-a3eb-b31e02b9dc96]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_f107384622ee8b2c_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
  `carto-un-eu.carto`.H3_FROMGEOGPOINT(
      geom, 9
    ) h3, *
  FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentes`;
END;

/*==================== native.isolines (v2) [ed10fa53-a7af-48eb-a3fd-f198fbeac3ab]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_6013105ac19a5b7f_6ef992b50024d076_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      
      CALL `carto-un-eu.carto`.CREATE_ISOLINES(
        'https://gcp-europe-west1.api.carto.com',
        'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI0YWI1NjU2MyJ9.4FGgabe5KvSsDwNc2FbUQv13eGFrFN3w828VXH1BT0s',
        'SELECT * FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales`',
        'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_6ef992b50024d076_result',
        'geom',
        'car',
        600,
        'time',
        '{"polygons_filter":{"limit":1},"carto_keep_orig_geom":true}');
      
    END;
  END IF;
END;
END;

/*==================== native.h3polyfill (v1) [205c15d7-9444-40f2-a7dd-78ffaa853c29]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_39c4ad73aac220bf_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH __h3 AS
  (
    SELECT
      s.carto_isoline_metadata, s.nombre,
      `carto-un-eu.carto`.H3_POLYFILL_MODE(
          geom,
          9,
          'center'
        ) h3s
    FROM
      (
        SELECT *
        FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_6ef992b50024d076_result`
        WHERE geom IS NOT NULL
      ) s
  )
  SELECT * EXCEPT(h3s)
  FROM __h3, __h3.h3s AS h3;
END;

/*==================== native.isolines (v2) [ce935e0b-178d-4399-82f7-05e561ad5ab7]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_6013105ac19a5b7f_d8a8ce1bc8ebe972_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      
      CALL `carto-un-eu.carto`.CREATE_ISOLINES(
        'https://gcp-europe-west1.api.carto.com',
        'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI0YWI1NjU2MyJ9.4FGgabe5KvSsDwNc2FbUQv13eGFrFN3w828VXH1BT0s',
        'SELECT * FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales`',
        'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_d8a8ce1bc8ebe972_result',
        'geom',
        'car',
        900,
        'time',
        '{"polygons_filter":{"limit":1},"carto_keep_orig_geom":true}');
      
    END;
  END IF;
END;
END;

/*==================== native.h3polyfill (v1) [4e789487-574a-4bb7-bea7-aace941b1364]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_fb7705bc12e217ad_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH __h3 AS
  (
    SELECT
      s.carto_isoline_metadata, s.nombre,
      `carto-un-eu.carto`.H3_POLYFILL_MODE(
          geom,
          9,
          'center'
        ) h3s
    FROM
      (
        SELECT *
        FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_d8a8ce1bc8ebe972_result`
        WHERE geom IS NOT NULL
      ) s
  )
  SELECT * EXCEPT(h3s)
  FROM __h3, __h3.h3s AS h3;
END;

/*==================== native.isolines (v2) [b68f7cf1-ae99-4782-8f41-be2aee72b337]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_6013105ac19a5b7f_933ce9f10a6c1043_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      
      CALL `carto-un-eu.carto`.CREATE_ISOLINES(
        'https://gcp-europe-west1.api.carto.com',
        'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI0YWI1NjU2MyJ9.4FGgabe5KvSsDwNc2FbUQv13eGFrFN3w828VXH1BT0s',
        'SELECT * FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales`',
        'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_933ce9f10a6c1043_result',
        'geom',
        'car',
        1800,
        'time',
        '{"polygons_filter":{"limit":1},"carto_keep_orig_geom":true}');
      
    END;
  END IF;
END;
END;

/*==================== native.h3polyfill (v1) [cffbea23-f119-4ec0-be9d-588fc34f2298]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_31ab0974b5839c55_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH __h3 AS
  (
    SELECT
      s.carto_isoline_metadata, s.nombre,
      `carto-un-eu.carto`.H3_POLYFILL_MODE(
          geom,
          9,
          'center'
        ) h3s
    FROM
      (
        SELECT *
        FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_933ce9f10a6c1043_result`
        WHERE geom IS NOT NULL
      ) s
  )
  SELECT * EXCEPT(h3s)
  FROM __h3, __h3.h3s AS h3;
END;

/*==================== native.isolines (v2) [cfa2a0b8-e5a4-46c5-8a6c-c31e637894db]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_6013105ac19a5b7f_e778c2b05f829258_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      
      CALL `carto-un-eu.carto`.CREATE_ISOLINES(
        'https://gcp-europe-west1.api.carto.com',
        'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI0YWI1NjU2MyJ9.4FGgabe5KvSsDwNc2FbUQv13eGFrFN3w828VXH1BT0s',
        'SELECT * FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales`',
        'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_e778c2b05f829258_result',
        'geom',
        'car',
        2700,
        'time',
        '{"polygons_filter":{"limit":1},"carto_keep_orig_geom":true}');
      
    END;
  END IF;
END;
END;

/*==================== native.h3polyfill (v1) [004e4be6-fbe3-4450-9f64-4a2d89c0d8bc]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_9330f325fd147eeb_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH __h3 AS
  (
    SELECT
      s.carto_isoline_metadata, s.nombre,
      `carto-un-eu.carto`.H3_POLYFILL_MODE(
          geom,
          9,
          'center'
        ) h3s
    FROM
      (
        SELECT *
        FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_e778c2b05f829258_result`
        WHERE geom IS NOT NULL
      ) s
  )
  SELECT * EXCEPT(h3s)
  FROM __h3, __h3.h3s AS h3;
END;

/*==================== native.isolines (v2) [32885080-3ff4-4aaa-8897-b042c3f300f0]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_6013105ac19a5b7f_fceaa5976fa1c6bc_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      
      CALL `carto-un-eu.carto`.CREATE_ISOLINES(
        'https://gcp-europe-west1.api.carto.com',
        'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfdDg3Mm81M2YiLCJqdGkiOiI0YWI1NjU2MyJ9.4FGgabe5KvSsDwNc2FbUQv13eGFrFN3w828VXH1BT0s',
        'SELECT * FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales`',
        'carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_fceaa5976fa1c6bc_result',
        'geom',
        'car',
        300,
        'time',
        '{"polygons_filter":{"limit":1},"carto_keep_orig_geom":true}');
      
    END;
  END IF;
END;
END;

/*==================== native.customsql (v2.0.0) [24c20f78-8a0f-4adf-bc34-847268a696d0]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_78cbfba00c14a127_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  
  SELECT
    *
  FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentes`
  WHERE num_expediente IN (
      SELECT DISTINCT num_expediente
      FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentalidad`
      WHERE lesividad_clasificada IN ('HERIDOS GRAVES', 'FALLECIDOS')
  );
END;

/*==================== native.saveastable (v1) [88854892-6b3f-4e26-bdd9-3539f7f267d2]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.accidentes_graves';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE IF NOT EXISTS `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_78cbfba00c14a127_result`''',
  '####',
  __destination
);
END;
END;

/*==================== native.h3polyfill (v1) [ccd37cd6-df63-4260-adcc-a946446f1c2c]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_e5780b987f14b0c6_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH __h3 AS
  (
    SELECT
      s.carto_isoline_metadata, s.nombre,
      `carto-un-eu.carto`.H3_POLYFILL_MODE(
          geom,
          9,
          'center'
        ) h3s
    FROM
      (
        SELECT *
        FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_fceaa5976fa1c6bc_result`
        WHERE geom IS NOT NULL
      ) s
  )
  SELECT * EXCEPT(h3s)
  FROM __h3, __h3.h3s AS h3;
END;

/*==================== native.h3frompoint (v1) [d6d75860-f169-43c9-9d09-27048dad5821]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_ae4ed3c75235b667_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
  `carto-un-eu.carto`.H3_FROMGEOGPOINT(
      geom, 9
    ) h3, *
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_78cbfba00c14a127_result`;
END;

/*==================== native.customsql (v2.0.0) [878ac897-6a31-498e-9e5b-ac8bcdaa02c0]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_21d2feaa8ef05412_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  
  WITH all_h3_times AS (
      SELECT h3, 300 as time FROM carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_e5780b987f14b0c6_result 
      UNION ALL
      SELECT h3, 600 as time FROM carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_39c4ad73aac220bf_result 
      UNION ALL
      SELECT h3, 900 as time FROM carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_fb7705bc12e217ad_result 
      
  ),
  
  min_time_per_h3 AS (
      SELECT h3, MIN(time) as min_time
      FROM all_h3_times
      GROUP BY h3
  )
  
  SELECT
      h3,
      CASE
          WHEN min_time = 300 THEN '00-05 min'
          WHEN min_time = 600 THEN '05-10 min'
          WHEN min_time = 900 THEN '10-15 min'
          
      END as catchment_zone
  FROM min_time_per_h3;
END;

/*==================== native.customsql (v2.0.0) [a2180ac3-b800-4452-9900-ecc5ded1656b]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_7dd4e5ceb1facac3_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT h3, catchment_zone FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_21d2feaa8ef05412_result`
  UNION ALL
  
  
  SELECT h3, '15-30 min' as catchment_zone
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_31ab0974b5839c55_result`
  WHERE h3 NOT IN (SELECT h3 FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_21d2feaa8ef05412_result`)
  UNION ALL
  
  SELECT h3, '30-45 min' as catchment_zone
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_9330f325fd147eeb_result`
  WHERE h3 NOT IN (SELECT h3 FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_31ab0974b5839c55_result`);
END;

/*==================== native.customsql (v2.0.0) [db7d52bb-1647-4c31-ab47-7d90d77c5667]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_31e65d4fca4a51d5_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH accidentes_simplificados AS (
      SELECT h3, num_expediente, tipo_accidente_clasificado FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_f107384622ee8b2c_result`
  ),
  graves_simplificados AS (
      SELECT h3, num_expediente FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_ae4ed3c75235b667_result`
  )
  
  SELECT
      a.h3, 
      a.catchment_zone,
      
      COALESCE(COUNT(DISTINCT s.num_expediente), 0) as volumen_total_accidentes,
      COALESCE(COUNT(DISTINCT g.num_expediente), 0) as severidad_alta,
      COALESCE(COUNT(DISTINCT CASE WHEN s.tipo_accidente_clasificado = 'Atropello a persona' THEN s.num_expediente END), 0) as riesgo_peatonal
  
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_7dd4e5ceb1facac3_result` a  
  LEFT JOIN accidentes_simplificados s ON a.h3 = s.h3
  LEFT JOIN graves_simplificados g ON a.h3 = g.h3
  GROUP BY
      a.h3, a.catchment_zone;
END;

/*==================== native.h3boundary (v1) [a911c403-f049-40a9-a734-8dc8827ea6af]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_3d3e59ba219f4a8f_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
    `carto-un-eu.carto`.H3_BOUNDARY(
        h3
    ) h3_geo, *
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_31e65d4fca4a51d5_result`;
END;

/*==================== native.customsql (v2.0.0) [2ed0caa1-0b01-426c-a624-a1bb62ea004f]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_1409a9083dc47efd_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH madrid_boundary AS (
      SELECT distritos_union AS boundary_geom FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.distritos_union` LIMIT 1
  )
  SELECT
      a.* EXCEPT(h3_geo),
      ST_INTERSECTION(a.h3_geo, b.boundary_geom) as geometry
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_3d3e59ba219f4a8f_result` a, madrid_boundary b
  WHERE ST_INTERSECTS(a.h3_geo, b.boundary_geom);
END;

/*==================== native.saveastable (v1) [1ab1f4e0-5c56-4a2e-a6a7-a1d7ca17bb69]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.perfil_riesgo_hospitales_madrid_por_hexagono';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE IF NOT EXISTS `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_6013105ac19a5b7f_1409a9083dc47efd_result`''',
  '####',
  __destination
);
END;
END;