/*
Code generated by Carto Workflows Engine (RUN)
- workflowid:2202f4ba-bee1-4ed2-8897-8a10c4321a1a
- versionid:0de029df103a99bf
- paramsid:97d170e1550eee4a
*/

/*==================== native.customsql (v2.0.0) [2c2accaa-ca7a-4149-acce-56e8485ccb25]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_e6e2dfef8ede4136_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
      ST_Union(ARRAY_AGG(geom)) AS distritos_union
  FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.distritos`;
END;

/*==================== native.customsql (v2.0.0) [bc587317-0b2a-47e8-8e59-0b11dbd2aee6]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_1c56880096e47d73_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  
  
  
  
  WITH
      _hospital_data_for_join AS ( 
          SELECT
              nombre,
              geom AS hospital_geom_for_join
          FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales` 
      ),
      _hospital_points_array AS ( 
          SELECT ARRAY_AGG(geom) AS points_array
          FROM `carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.hospitales`
      ),
      _madrid_boundary_polygon_cte AS ( 
          SELECT distritos_union AS boundary_poly 
          FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_e6e2dfef8ede4136_result`
          LIMIT 1
      ),
      _madrid_bbox_struct AS ( 
          SELECT ST_BOUNDINGBOX(boundary_poly) AS bbox_struct
          FROM _madrid_boundary_polygon_cte
      ),
      _madrid_boundary_bbox_coords AS ( 
          SELECT
              [
                  bbox_struct.xmin,
                  bbox_struct.ymin,
                  bbox_struct.xmax,
                  bbox_struct.ymax
              ] AS bbox_array
          FROM _madrid_bbox_struct
      ),
      _voronoi_tessellation_geoms AS ( 
          SELECT
              voronoi_cell AS voronoi_geom_raw
          FROM
              (SELECT
                  `carto-un-eu.carto`.ST_VORONOIPOLYGONS(
                      (SELECT points_array FROM _hospital_points_array),
                      (SELECT bbox_array FROM _madrid_boundary_bbox_coords)
                  ) AS voronoi_collection
              ),
              UNNEST(voronoi_collection) AS voronoi_cell
      )
  
  SELECT
      h_join.nombre, 
      vg.voronoi_geom_raw AS voronoi_geom_extendido 
  FROM
      _voronoi_tessellation_geoms vg
  JOIN
      _hospital_data_for_join h_join ON ST_CONTAINS(vg.voronoi_geom_raw, h_join.hospital_geom_for_join);
END;

/*==================== native.intersection (v1) [595678c5-6ddb-41d4-a987-7ea19f6cdb6d]  ====================*/
BEGIN
DECLARE alias STRING;

EXECUTE IMMEDIATE
'''
  with __alias AS(
    SELECT CONCAT(
      'b.', column_name, ' AS ', column_name, '_secondary'
    ) col_alias
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3`.INFORMATION_SCHEMA.COLUMNS
  WHERE table_name = 'WORKFLOW_b4e0f7e821e5c553_e6e2dfef8ede4136_result'
  )
  SELECT STRING_AGG(col_alias, ', ')
  FROM __alias
'''
INTO alias;

EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_286404bc423cc563_result`
  OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(
      CURRENT_TIMESTAMP(), INTERVAL 30 DAY
    )
  )
  AS
    SELECT
      ST_INTERSECTION(
        b.distritos_union,
        a.voronoi_geom_extendido
      )
    AS intersection_voronoi_geom_extendido_distritos_union,
      a.*, %s
    FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_1c56880096e47d73_result` AS a
    JOIN `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_e6e2dfef8ede4136_result` AS b
    ON ST_INTERSECTS(
      b.distritos_union,
      a.voronoi_geom_extendido
    )''',
  '%s',
  alias
);
END;

/*==================== native.dropcolumn (v1) [d07d77d1-28e7-48d8-baf0-4837ff2e02a3]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_630db1ab369e167a_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (voronoi_geom_extendido, distritos_union_secondary)
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_286404bc423cc563_result`;
END;

/*==================== native.renamecolumn (v1) [ba7c3b87-aec8-4857-bf17-ffe6b325fd37]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_478a3f591e217766_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (intersection_voronoi_geom_extendido_distritos_union),
    intersection_voronoi_geom_extendido_distritos_union AS voronoi_distritos_cell
  FROM `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_630db1ab369e167a_result`;
END;

/*==================== native.saveastable (v1) [6689b5b2-4c83-47d6-93c9-968dbfffc337]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.voronoi';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE IF NOT EXISTS `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_478a3f591e217766_result`''',
  '####',
  __destination
);
END;
END;

/*==================== native.saveastable (v1) [788b8704-bf5c-48fa-87d4-7db50f28ffa0]  ====================*/
BEGIN
DECLARE __destination STRING DEFAULT 'carto-dw-ac-t872o53f.private_jorgekk22_3000e6c3.distritos_union';
BEGIN
EXECUTE IMMEDIATE
REPLACE(
  '''DROP TABLE IF EXISTS `####`''',
  '####',
  __destination
);
EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE IF NOT EXISTS `####`
  CLONE `carto-dw-ac-t872o53f.workflows_temp_jorgekk22_3000e6c3.WORKFLOW_b4e0f7e821e5c553_e6e2dfef8ede4136_result`''',
  '####',
  __destination
);
END;
END;